import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ClipboardList, Loader2, Mail, Phone } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

const statusLabel: Record<string, string> = { new: "Nieuw", in_progress: "In behandeling", contacted: "Benaderd", closed: "Gesloten" };
const intentLabel: Record<string, string> = { purchase: "Aankoop", fleet: "Zakelijk / fleet", service: "Service", general: "Algemeen" };

export default function LeadInbox() {
  const utils = trpc.useUtils();
  const active = trpc.organizations.active.useQuery();
  const [organizationId, setOrganizationId] = useState(0);
  useEffect(() => { if (active.data?.organization.id) setOrganizationId(active.data.organization.id); }, [active.data?.organization.id]);
  const leads = trpc.website.leads.useQuery({ organizationId }, { enabled: organizationId > 0 });
  const update = trpc.website.updateLeadStatus.useMutation({ onSuccess: () => { toast.success("Leadstatus bijgewerkt."); void utils.website.leads.invalidate(); }, onError: (error) => toast.error(error.message) });
  if (active.isLoading || leads.isLoading) return <DashboardLayout><div className="grid min-h-[45vh] place-items-center"><Loader2 className="size-6 animate-spin text-cyan-700" /></div></DashboardLayout>;
  if (!active.data) return <DashboardLayout><p className="rounded-2xl bg-white p-8 text-slate-600">Maak eerst een organisatie aan om websiteleads te bekijken.</p></DashboardLayout>;
  return <DashboardLayout><div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-700">Opvolging</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Websiteleads</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Alleen bezoekers die toestemming gaven om gecontacteerd te worden verschijnen hier. Deze leads blijven gekoppeld aan de actieve organisatie.</p></div>{leads.data?.length ? <div className="grid gap-4">{leads.data.map((lead) => <article key={lead.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap gap-2"><Badge variant="outline" className="border-cyan-200 bg-cyan-50 text-cyan-800">{intentLabel[lead.intent]}</Badge><Badge variant="outline" className="border-slate-200 bg-slate-50 text-slate-600">{statusLabel[lead.status]}</Badge></div><h2 className="mt-4 text-lg font-semibold text-slate-900">{lead.name}</h2><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-sm text-slate-600"><a href={`mailto:${lead.email}`} className="inline-flex items-center gap-1.5 hover:text-cyan-700"><Mail className="size-3.5" />{lead.email}</a>{lead.phone ? <a href={`tel:${lead.phone}`} className="inline-flex items-center gap-1.5 hover:text-cyan-700"><Phone className="size-3.5" />{lead.phone}</a> : null}</div><p className="mt-4 max-w-3xl rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-700">{lead.message}</p><p className="mt-3 text-xs text-slate-500">Toestemming gegeven op {new Date(lead.consentAt).toLocaleString("nl-NL", { dateStyle: "medium", timeStyle: "short" })}</p></div><label className="grid gap-2 text-sm font-medium text-slate-700">Status<select value={lead.status} onChange={(event) => update.mutate({ organizationId, leadId: lead.id, status: event.target.value as "new" | "in_progress" | "contacted" | "closed" })} disabled={update.isPending} className="h-10 min-w-44 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="new">Nieuw</option><option value="in_progress">In behandeling</option><option value="contacted">Benaderd</option><option value="closed">Gesloten</option></select></label></div></article>)}</div> : <section className="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-slate-100 text-slate-600"><ClipboardList className="size-6" /></span><h2 className="mt-5 text-lg font-semibold text-slate-900">Nog geen websiteleads</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">Zodra een bezoeker van EasyWiel toestemming geeft voor contact, verschijnt de aanvraag hier voor opvolging.</p><Button onClick={() => window.location.assign("/websitebot")} variant="outline" className="mt-6"><CheckCircle2 className="size-4" /> Websitebot openen</Button></section>}</DashboardLayout>;
}
